#docker swarm init
#docker stack deploy eventual -c docker-compose.yaml
#docker service ls
#docker swarm leave --force

version: '3'

services:
  # cf. https://hub.docker.com/_/mongo
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - "27017:27017" # mongo default port
    command: --journal
    user: "1000:1000"

  # cf. https://hub.docker.com/_/mongo-express
  mongo-dashboard:
    depends_on:
      - mongodb
    image: mongo-express
    restart: always
    ports:
      - "8081:8081" # mongo bashboard port
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb #nome immagine che corrisponde all'IP grazie al dns di docker
      ME_CONFIG_MONGODB_PORT: 27017  #mongodb port
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_SERVER}:${ME_CONFIG_MONGODB_PORT}/

  eventual-backend:
    depends_on:
      - mongodb
    image: node-eventual
    environment:
      MONGO_HOST: mongodb #nome immagine che corrisponde all'IP grazie al dns di docker
    ports:
      - "8082:8080"
    restart: always
    #deploy:
      #mode: replicated
      #replicas: 3

  eventual-frontend:
    depends_on:
      - eventual-backend
    image: react-eventual
    ports:
      - "3000:3000"
    restart: always

