version: '3.1'

services:
  # cf. https://hub.docker.com/_/mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # mongo admin username
      MONGO_INITDB_ROOT_PASSWORD: admin # mongo admin password
    ports:
      - 27017:27017 # mongo default port

  # cf. https://hub.docker.com/_/mongo-express
  mongo-dashboard:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 # mongo bashboard port
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin # same mongo username as above
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin # same mongo password as above
      ME_CONFIG_MONGODB_SERVER: mongo #nome immagine che corrisponde all'IP grazie al dns di docker
      ME_CONFIG_MONGODB_PORT: 27017  #mongodb port
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@${ME_CONFIG_MONGODB_SERVER}:${ME_CONFIG_MONGODB_PORT}/

  hc-frontend:
    depends_on:
      - mongo
    image: foscofra/node-eventual
    #image: foscofra/nodejs
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_HOST: mongo #nome immagine che corrisponde all'IP grazie al dns di docker
    ports:
      - "8082:8080"
    restart: always
    deploy:
      mode: replicated
      replicas: 3
